### ISSUE TITLE
Add --non-interactive for scripts

### ISSUE THREAD

**Issue by Jean28518** [openSUSE/opi#117]
Great project!

would love to see a '--non-interactive' option like in zypper, that I can use this in my scripts.

**Comment by asvetter** [comment]
I think it would be good, if opi would hand through more options (maybe all unknown) to zypper.

**Comment by asdil12** [comment]
The question is how opi should resolve all the questions it asks the user, if a non interactive mode is introduced.

**Comment by 13werwolf13** [comment]
> The question is how opi should resolve all the questions it asks the user, if a non interactive mode is introduced.

I think I have the answer to this question:

if there is a complete match in the package name with the request, then select it, otherwise the message "cannot be delivered in non-interactive mode"

if there is a match in the repositories available in the default distribution, then select it, otherwise display the message "cannot be installed in non-interactive mode"

and I'm pretty sure non-interactive mode should avoid `Home:` repositories
