### ISSUE TITLE
"copyq" original RPM not included

### ISSUE THREAD

**Issue by RafaelLinux** [openSUSE/opi#162]
Hello

When I search for "copyq" with `opi`, all results belong to non official repositories. 
```
 opi copyq
1. copyq
2. copyq5
3. copyq5-doc
4. copyq5-lang
5. copyq-debuginfo
6. copyq-debugsource
Pick a number (0 to quit): 1
You have selected package name: copyq
1. home:X0F:HSF !                            | 7.1.0                     | x86_64
2. home:vibondare !                          | 7.1.0                     | x86_64
3. home:rickyk !                             | 3.13.0                    | x86_64
4. home:frispete:Tumbleweed !                | 7.1.0                     | x86_64
5. home:lukho:copyq !                        | 7.1.0                     | x86_64
6. home:tecosaur !                           | 7.1.0                     | x86_64
7. home:frispete:PyQt5 !                     | 7.0.0                     | x86_64
8. home:lukho:copyq-beta !                   | 6.3.2.r39.gdbecf3b3       | x86_64
9. home:limon !                              | 6.2.0                     | x86_64
Pick a number (0 to quit):
```
However in ["copyq" GITHUB](https://github.com/hluk/CopyQ/releases) page, they have available LEAP and Tumbleweed RPMs files.

Please, could you add that "official" version to `opi`?

Thank you

**Comment by asdil12** [comment]
Normally I would say that is because there is no plugin (like for maptool) that would download and install the rpm from github.
But the funny thing here is, that the people from people from https://github.com/hluk/CopyQ actually build the RPM that they include in their github releases using the openSUSE build service:
https://build.opensuse.org/project/show/home:lukho:copyq

So you could simply select the entry
```
5. home:lukho:copyq !                        | 7.1.0                     | x86_64
```
in the opi list and get the very same package (and automatic updates if you keep the repo).

The `Vendor` field in the RPM provided by them on their github release indicates, that is was build in this OBS repo:
```
$ wget https://github.com/hluk/CopyQ/releases/download/v7.1.0/copyq_7.1.0_openSUSE_Leap_15.4.x86_64.rpm
[...]
2023-11-17 14:01:34 (426 KB/s) - »copyq_7.1.0_openSUSE_Leap_15.4.x86_64.rpm« gespeichert [2385276/2385276]

$ rpm -qi copyq_7.1.0_openSUSE_Leap_15.4.x86_64.rpm
warning: copyq_7.1.0_openSUSE_Leap_15.4.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 04812769: NOKEY
Name        : copyq
Version     : 7.1.0
Release     : lp154.1.1
Architecture: x86_64
Install Date: (not installed)
Group       : Productivity/Text/Utilities
Size        : 10112587
License     : GPL-3.0-or-later
Signature   : RSA/SHA256, So 03 Sep 2023 09:58:28 CEST, Key ID 738c9b4204812769
Source RPM  : copyq-7.1.0-lp154.1.1.src.rpm
Build Date  : So 03 Sep 2023 09:58:15 CEST
Build Host  : i04-ch2d
Packager    : https://www.suse.com/
Vendor      : obs://build.opensuse.org/home:lukho
URL         : https://hluk.github.io/CopyQ/
Summary     : Advanced clipboard manager
Description :
CopyQ is advanced clipboard manager with searchable and editable history with
support for image formats, command line control and more.
Distribution: home:lukho:copyq / 15.4
```

Maybe you could create a submit request from this above linked OBS repo to `X11:Utilities` (I guess that would be the right repo).
If that is accepted (maybe some changes are requested), you could submit from there to `openSUSE:Factory` which would result in this package getting into Tumbleweed (and then also into the next Leap release.

**Comment by RafaelLinux** [comment]
Thank you very much for all the research. I will suggest to the openSUSE maintainers to include it, although I fear that it will happen like KSnip (on which Spectacle was based) and that copyQ will possibly be rejected because it will not use the latest KDE libraries or be compatible with Wayland.

In any case, thanks for informing me which would be the correct option (lukho) of the ones shown by "opi".

**Comment by asdil12** [comment]
> In any case, thanks for informing me which would be the correct option (lukho) of the ones shown by "opi".

home:lukho:copyq
