### ISSUE TITLE
Suggestion: use $releasever when adding Packman

### ISSUE THREAD

**Issue by surprized** [openSUSE/opi#32]
From YaST, when adding Packman using the url "https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_$releasever/" a raw url string is stored, not sure for what purpose but probably done so the system knows how to handle update the repos along a dup.
When using "opi packman" this string is not stored, as, I belive the added repo uses 15.2 instead of $releasever.

Try this to see it in action:
`sudo zypper addrepo -cfp 90 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_$releasever/' packman`
The quotes in the url are required.

From YaST, here's what the repo looks like
`Raw name:` 
`URL: https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_15.2/`
`Raw URL: https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_$releasever/`

(probably something could be done about Raw name as well)

**Comment by guoyunhe** [comment]
This probably only works for Leap. In Tumbleweed, `$releasever` is empty. I don't know when this parameter is introduced and if it works on older Leap releases, like 15.0. It is not safe to use a variable that isn't well documented, because it can change or disappear. By using hard-coded URLs, it will never fail.

I was actually planning to make another script to make Leap upgrade easier. It should solve the problem of `zypper dup`.
