### ISSUE TITLE
Search is broken?

### ISSUE THREAD

**Issue by RDKRACZ** [openSUSE/opi#86]
Search does not return some results that are shown on the obs website.
![Screenshot_20211221_140513](https://user-images.githubusercontent.com/43277609/146935035-e8f93f2b-f5f0-45ca-b94b-6ad992bf5fc2.png)
https://build.opensuse.org/package/show/openSUSE:Factory/pcmanfm-qt
https://build.opensuse.org/package/show/openSUSE:Backports:SLE-15-SP4/pcmanfm-qt

**Comment by RDKRACZ** [comment]
![Screenshot_20211221_140920](https://user-images.githubusercontent.com/43277609/146935383-01c9ee1d-3b67-433c-ba74-389fc73959d3.png)
![Screenshot_20211221_140910](https://user-images.githubusercontent.com/43277609/146935378-ee4164cd-b681-4b7e-9e56-b482406d0756.png)

**Comment by asdil12** [comment]
`opi` will only show repos in the search results, where the requested package (`pcmanfm` in this case) is actually built and published for the distribution you are using.
You are eg. not seeing the openSUSE:Backports:SLE-15-SP4 repo, because this repo only builds for SLE15SP4/Leap15.4 (even though I'm not sure if that repo would publish stuff anyway) and you are using Leap 15.3 if I see this correctly.
